jobs:
  build:
    working_directory: ~/ethereumex
    docker:
      - image: elixir:latest
      - image: parity/parity:v1.7.2

    steps:
      - checkout
      - restore_cache:
          key: _build
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix dialyzer
      - run: mix test --include eth --include batch
      - save_cache:
          key: _build
          paths:
            - _build